# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Bus_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 201)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 160, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.label_2.setObjectName("label_2")
        self.obj_bus_date = QtWidgets.QDateTimeEdit(Dialog)
        self.obj_bus_date.setGeometry(QtCore.QRect(180, 90, 201, 22))
        self.obj_bus_date.setCalendarPopup(True)
        self.obj_bus_date.setTime(QtCore.QTime(8,0,0))
        self.obj_bus_date.setDate(QtCore.QDate.currentDate())
        self.obj_bus_date.setObjectName("obj_bus_date")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 111, 21))
        self.label_3.setObjectName("label_3")
        self.obj_bus_place = QtWidgets.QSpinBox(Dialog)
        self.obj_bus_place.setGeometry(QtCore.QRect(180, 60, 201, 22))
        self.obj_bus_place.setProperty("value", 59)
        self.obj_bus_place.setObjectName("obj_bus_place")
        self.obj_bus_nom = QtWidgets.QLineEdit(Dialog)
        self.obj_bus_nom.setGeometry(QtCore.QRect(180, 30, 201, 20))
        self.obj_bus_nom.setObjectName("obj_bus_nom")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 111, 21))
        self.label_4.setObjectName("label_4")
        self.obj_bus_desti = QtWidgets.QComboBox(Dialog)
        self.obj_bus_desti.setGeometry(QtCore.QRect(180, 120, 201, 22))
        self.obj_bus_desti.setObjectName("obj_bus_desti")
        self.obj_bus_desti.addItem("")
        self.obj_bus_desti.addItem("")
        self.obj_bus_desti.addItem("")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ajouter un bus"))
        self.label.setText(_translate("Dialog", "Nom : "))
        self.label_2.setText(_translate("Dialog", "Nombre de place :"))
        self.label_3.setText(_translate("Dialog", "Date / Heure "))
        self.label_4.setText(_translate("Dialog", "Destination :"))
        self.obj_bus_desti.setItemText(0, _translate("Dialog", "Priay"))
        self.obj_bus_desti.setItemText(1, _translate("Dialog", "Gevrieux"))
        self.obj_bus_desti.setItemText(2, _translate("Dialog", "Chazey"))
