# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Client_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(476, 245)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(160, 190, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.obj_client_nom = QtWidgets.QLineEdit(Dialog)
        self.obj_client_nom.setGeometry(QtCore.QRect(140, 60, 321, 20))
        self.obj_client_nom.setObjectName("obj_client_nom")
        self.obj_client_tel = QtWidgets.QLineEdit(Dialog)
        self.obj_client_tel.setGeometry(QtCore.QRect(140, 140, 321, 20))
        self.obj_client_tel.setObjectName("obj_client_tel")
        self.obj_client_prenom = QtWidgets.QLineEdit(Dialog)
        self.obj_client_prenom.setGeometry(QtCore.QRect(140, 100, 321, 20))
        self.obj_client_prenom.setObjectName("obj_client_prenom")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 60, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 111, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ajouter un client "))
        self.label.setText(_translate("Dialog", "Nom : "))
        self.label_2.setText(_translate("Dialog", "Prénom : "))
        self.label_3.setText(_translate("Dialog", "Téléphone : "))
